---
title: "Short-sighted evolution of Influenza cellular receptor binding avidity shapes influenza epidemic dynamics"
subtitle: "Within-host dynamics of influenza virus adaptation"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Description of within-host model}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
library(driftSim)
knitr::opts_chunk$set(echo = TRUE, fig.width=7,fig.height=6,
                      message=FALSE, results=FALSE,warning=FALSE)
```

## Foreword
The purpose of this vignette is to describe the theory behind the model of the [driftSim](http://www.github.com/jameshay218/driftSim) package. Here, we will describe the model that governs the within-host dynamics of influenza binding avidity adaptation. Another way of understanding these equations is to check out the second (parameters) panel of the `driftSim` shiny app, which can be run with `driftSim::runSimulationApp()`. A useful piece of background reading can be found in a paper by [Yuan et al](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3678328/).

Note that this document does not describe the transmission model itself, which is described [here](https://jameshay218.github.io/driftSim/inst/doc/transmission_model.html).

## Model equations
The plots in the shiny app are governed by the equations shown below. These equations make up a model to represent how changes in binding avidity impact the various stages from host infection through to reinfection. The model also considers the immune history of the host, $\textbf{h}$, and the level of immunity, $k$, a host has, which is represented by the blue-red lines in the plots (blue $k=0$, red $k=k_{max}$). For the purposes of these plots, a higher value of $k$ simply represents higher levels of antibody-mediated immunity.

### 1. Probability of evading immune system
After entering a host, the virus must first evade the immune response (Equation 1). Here, the probability of escaping the immune response increases as binding avidity increases as shown in plot C. The virus must also evade the host's antibody-mediated immunity conferred from all previous infections ($\textbf{h}$), adjusted by the antigenic distance between the infecting virus and the viruses that elicited the host's previous antibody response.

As hosts will have encountered a number of infections in their lifetime, the infection history $\textbf{h}$ for a given host is the vector of all viruses that the host has seen. This part of the model is described in greater detail in [Section 3.3 of the accompanying transmission model vignette](https://jameshay218.github.io/driftSim/inst/doc/transmission_model.html). 

In summary, the level of immunity that a host has against an infecting virus is the sum of the host's antibody repetoire less the minimum antigenic distance between the infecting virus and all past infections in the host's immune history, represented by the term $r(k - \delta_{ij})$ below. $i$ represents the infecting strain and $j$ represents the most antigenically similar strain in the host's infection history. The definition of antigenic distance is analagous to the concepts described by [Smith et al. 2004](http://science.sciencemag.org/content/305/5682/371)

The rate of change of $f$ with respect to binding avidity is shown in plot E.

\begin{equation}
  f(k,\delta_{ij},V_i) = [1-e^{-p(V_i+q)}]^{r(k - \delta_{ij})}
\end{equation}

Where $V_i$ is the binding avidity of virus $i$; $k$ is the total antibody titre of the host; $\delta_{ij}$ is the antigenic distance between strain $i$ and the host immunity virus, $j$; and the remaining parameters are defined at the bottom of this document (or with `?exampleParameters` from the package).

### 2. Probability of successful replication within host
Binding avidity also affects how well a virus is able to replicate within the host, as described by Equation 2. This relationship is shown in plot A. The naive case (ie. $k=0$) is shown in plot D.

\begin{equation}
g(V_i) = e^{-aV_i^b}
\end{equation}


### 3. Probability of successful within host infection
To successfully infect a host, the virus must escape the immune system (Equation 1) and successfully replicate (Equation 2). The probability of a successful within-host infection is given by:
\begin{equation}
\phi(H_k,V_i) = f(k,\delta_{ij},V_i) \cdot g(V_i) = [1-e^{-p(V_i+q)}]^{r(k - \delta_{ij})} \cdot e^{-aV_i^b}
\end{equation}

Where $H_k$ represents the host with immunity $k$ and a known infection history such that $H_k : \{k, \delta_{ij}\}$.

### 4. Within host reproductive number
The within-host reproductive number is given by the product of the probability of successful within host infection, and the number of offspring virions produced per event:
\begin{equation}
  R_{in} = n \cdot \phi(H_k,V_i)
\end{equation}

### 5. Infectiousness
The infectiousness of a particular virus is therefore related to the within-host reproductive number and the number of initially infecting virions as follows:
\begin{equation}
\rho = 1 - (\frac{1}{R_{in}})^{-v} = 1-(\frac{1}{\phi(H_k, V_i)})^{-nv}
\end{equation}

### 6. Transmission rate
The transmission rate between hosts, $\beta$, is therefore given by the product of the infectiousness of that virus and the contact rate between hosts. This relationship is shown in plot B. The rate of change of $\beta$ with respect to binding avidity is shown in plot F.
\begin{equation}
\beta = c \cdot \rho
\end{equation}

## 7. Derivatives
The rate of binding avidity adaptation of a virus within a given host is assumed to be proportional to the derivate of $R_{in}$ with respect to binding avidity:

\begin{equation}
\frac{dV}{dt} = \frac{dR_{in}}{dV} = g(V_i)f'(J,V_i) + g'(V_i)f(J,V_i)
\end{equation}

Where $J = k - \delta_{ij}$, and the derivaties for $g(V)$ and $f(J, V)$ are given by:

\begin{equation}
g'(V) = -abV^{b-1}e^{-a(V^b)}\\
f'(J, V) = prJ(1-e^{-p(V+q)})^{rJ-1}e^{-p(V + q)}
\end{equation}

## Parameter descriptions
* $p$: parameter to control degree by which changes in binding avidity affect probability of escape from immune response
* $r$: parameter to control degree by which previous exposure reduce probability of immune escape
* $b$: parameter to control the shape of the relationship between probability of successful replication and changes in binding avidity
* $a$: controls rate of changes of relationship between probability of successful replication and change in binding avidity
* $c$: per day contact rate
* $n$: number of offspring per virus replication event
* $v$: number of virions initially transmitted
* $q$: parameter to control the shape of the relationship between binding avidity and immune escape (shift on the x-axis)
* $\delta$: antigenic distance between two viruses

