# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve viral kinetics
#'
#' @export
solve_viral_kinetics_cpp <- function(times, tg, tp, to, tw, alpha, infectiousnessMax, infectiousnessGradient, infectiousnessInflection) {
    .Call('_driftSim_solve_viral_kinetics_cpp', PACKAGE = 'driftSim', times, tg, tp, to, tw, alpha, infectiousnessMax, infectiousnessGradient, infectiousnessInflection)
}

#' Solve infectiousness
#'
#' @export
solve_infectiousness_cpp <- function(times, tg, tp, to, tw, alpha, infectiousnessMax, infectiousnessGradient, infectiousnessInflection) {
    .Call('_driftSim_solve_infectiousness_cpp', PACKAGE = 'driftSim', times, tg, tp, to, tw, alpha, infectiousnessMax, infectiousnessGradient, infectiousnessInflection)
}

#' Interface to the entire C++ driftSim simulation
#'
#' @param flags set of boolean flags for simulation output. See \code{\link{run_simulation}}
#' @param hostPopn vector of parameters related to the host population. See \code{\link{run_simulation}}
#' @param seeds Matrix of parameters related to epidemic seeding. See \code{\link{run_simulation}}
#' @param vlPars Matrix of parameters related to the viral load kinetics. See \code{\link{run_simulation}}
#' @param infectiousnessPars Matrix of parameters related to the variant-specific infectiousness. See \code{\link{run_simulation}}
#' @param crossImmunity Matrix of parameters related to variant cross immunity. See \code{\link{run_simulation}}
#' @param day double of simulation starting day
#' @param final_day double of simulation final day (steps of 1 day)
#' @param tstep double of simulation time steps
#' @param output_files vector of output file names, as in \code{\link{run_simulation}}
#' @param VERBOSE boolean to indicate how much console output the simulation should have
#' @param scenario integer 1 to 4, indicating which version of the model is being run. See \code{\link{scenario_descriptions}} for a description of each scenario
#' @param callback pointer to enable call backs to R. Pretty much just for progress bar in the shiny app
#' @return the final virus ID from the simulation
#' @export
#' @useDynLib driftSim
run_simulation_cpp <- function(flags, hostPopn, seeds, vlPars, infectiousnessPars, crossImmunity, ageDistribution, infectivityCurve, susceptibilityCurve, day, final_day, tstep, output_files, VERBOSE, callback) {
    .Call('_driftSim_run_simulation_cpp', PACKAGE = 'driftSim', flags, hostPopn, seeds, vlPars, infectiousnessPars, crossImmunity, ageDistribution, infectivityCurve, susceptibilityCurve, day, final_day, tstep, output_files, VERBOSE, callback)
}

