# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interface to the entire C++ driftSim simulation
#'
#' @param flags set of boolean flags for simulation output. See \code{\link{run_simulation}}
#' @param hostPopn vector of parameters related to the host population. See \code{\link{run_simulation}}
#' @param vlPars Matrix of parameters related to the iviral load kinetics. See \code{\link{run_simulation}}
#' @param day integer of simulation starting day
#' @param final_day integer of simulation final day (steps of 1 day)
#' @param output_files vector of output file names, as in \code{\link{run_simulation}}
#' @param VERBOSE boolean to indicate how much console output the simulation should have
#' @param scenario integer 1 to 4, indicating which version of the model is being run. See \code{\link{scenario_descriptions}} for a description of each scenario
#' @param callback pointer to enable call backs to R. Pretty much just for progress bar in the shiny app
#' @return the final virus ID from the simulation
#' @export
#' @useDynLib driftSim
run_simulation_cpp <- function(flags, hostPopn, vlPars, infectiousnessPars, crossImmunity, day, final_day, output_files, VERBOSE, callback) {
    .Call('_driftSim_run_simulation_cpp', PACKAGE = 'driftSim', flags, hostPopn, vlPars, infectiousnessPars, crossImmunity, day, final_day, output_files, VERBOSE, callback)
}

